version: "3.3"
services:
  nginxproxy:
    image: nginx
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./Certbot/certificate:/certificate
      - ./conf.d:/etc/nginx/conf.d